### ISSUE TITLE
Type conversion from 'half'  to 'OpTypeFloat 32' should be retained.

### ISSUE THREAD

**Issue by whenimg0ne** [google/DirectXShaderCompiler#155]
Hello, 

`docs/SPIR-V.rst` states that the normal scalar type `half` is mapped to `OpTypeFloat 16`.  According to [the MSDN documentation for Scalar Types in HLSL](https://msdn.microsoft.com/en-us/library/windows/desktop/bb509646(v=vs.85).aspx) , `half` is treated as `float` nowadays.  
  
In fact, however, current implementation for SPIR-V emitter is treating `half` type as `OpTypeFloat 32`, not `OpTypeFloat 16`.
This result is caused by resolving `half` to its canonical type `float` in [TypeTranslator::translateType()](https://github.com/Microsoft/DirectXShaderCompiler/blob/d98d66564a8314639f13ae23b8b049c99b21d867/tools/clang/lib/SPIRV/TypeTranslator.cpp#L19).  
  
Is this intended implementation?  If not, I think current behavior should be retained due to the MSDN documentation.  If so, could you update `docs/SPIR-V.rst` ?
  
Thanks.

P.S.  
I'm really happy that SPIR-V emitter is coming to DirectXShaderCompiler!

**Comment by antiagainst** [comment]
Hi @whenimg0ne!

I'm very glad to hear that you have tried out and are happy with SPIR-V codegen. :)

Actually, we haven't "officially" supported `half` yet (there are no tests existing for it in [CodeGenSPIRV](https://github.com/google/DirectXShaderCompiler/tree/spirv/tools/clang/test/CodeGenSPIRV)). The mentioning of `half` in SPIR-V.rst is from the very beginning when we just started working on the emitter and apparently outdated. We'll respect MSDN doc and update SPIR-V.rst.

Generally the SPIR-V.rst is a little bit lagged behind. We are busy uploading all stashed commits to the upstream (you can see lots of commits w.r.t. SPIR-V in the upstream [master](https://github.com/Microsoft/DirectXShaderCompiler/commits/master). After that, we'll give another round of doc updating about steps to build & contribute, and how we map all implemented features. Thanks and stay tuned! :)

**Comment by whenimg0ne** [comment]
Hi @antiagainst!

Oh, my bad.  I haven't looked for test codes thus didn't know that `half` is not officially supported yet.  
  
Thank you for sharing detailed status about SPIR-V.rst and the project.  
I'm looking forward to see and try out SPIR-V codegen when any of your works has merged into master!

I appreciate your quick reply.

**Comment by antiagainst** [comment]
@whenimg0ne: Just wanted to let you know that this pull request (https://github.com/Microsoft/DirectXShaderCompiler/pull/596) will update the doc to reflect the current state.
