### ISSUE TITLE
[linux-port] Fix GCC compile errors

### ISSUE THREAD

**Issue by ehsannas** [google/DirectXShaderCompiler#184]
Currently the Linux builds using clang are passing, but builds using gcc are failing.

@pow2clk, would you please send PRs to fix the gcc builds? It'd be great to see a green check-mark from the Travis Linux buildbots.

**Comment by pow2clk** [comment]
I think this is done? I don't know anything else to do with it. I submitted a PR for GCC5, but that has its own issue really.

**Comment by antiagainst** [comment]
Yes. I'll close this. Thanks!
