### ISSUE TITLE
Thread-safe mechanisms not fully implemented on non-Win32

### ISSUE THREAD

**Issue by pow2clk** [google/DirectXShaderCompiler#198]
InterlockedIncrement and InterlockedDecrement are atomic operations to increment or decrement the value pointed to by the pointer parameter and return the same. Currently they are implemented as simple addition operations in WinMacros.h for non-win32 platforms which works well enough, but wasn't really the original intent.

InitializeCriticalSection, DeleteCriticalSection, EnterCriticalSection, and  LeaveCriticalSection serve to create a mutual exclusion section of code, but they are also stubbed out currently. 

There are already platform abstractions available to LLVM in Atomics.h and Mutex.h respectively. I propose we leverage them.

**Comment by ehsannas** [comment]
+1

**Comment by ehsannas** [comment]
@pow2clk is there any work left associated with this case?

**Comment by pow2clk** [comment]
Nope! I've finished everything I intended to with this.
