### ISSUE TITLE
Better naming for WinTypes, WinMacros, WinSAL ?

### ISSUE THREAD

**Issue by ehsannas** [google/DirectXShaderCompiler#232]
WinTypes.h, WinMacros.h and WinSAL.h files may be confusing for someone developing on Linux?

Perhaps we should merge them into one file and call it something like WinAdapter.h.

**Comment by pow2clk** [comment]
I think lei proposed merging them into one, which is fine. I like WinAdapter better than just Win*. I was thinking of something like "Windows on Linux" abbreviated to WOL, but I'm not particular about naming in general provided it's not apt to be mistaken for something else.

**Comment by antiagainst** [comment]
+1 to `WinAdapter.h`

For "Windows on Linux", I think maybe "Windows on Unix" is better.

**Comment by pow2clk** [comment]
WinAdapter seems to have won out. I'm fine with that.

**Comment by ehsannas** [comment]
Fixed by #237
