### ISSUE TITLE
-Fo creates files with zero permissions

### ISSUE THREAD

**Issue by ehsannas** [google/DirectXShaderCompiler#260]
Looks like we have had a regression. I just tried -Fo option, and the file that was created was empty. It happened for both DXIL and SPIRV.

I am sure this was working in the past. So most likely we've had a regression somewhere. This shows that anything you don't test will break! :)

We should also add this as a test to our bots.

**Comment by pow2clk** [comment]
That's strange I do run a test using this regularly and it still seems to be working for me. 

Now you mention it and now I test it for something fresh, I did notice at one point when files are being created originally, they have their permissions set all to zero on Linux. Can you give more information about what you're observing? 

I'm running `dxc -T ps_6_0 utils/hct/smoke.hlsl -Fo smoke.psv -spirv`

>ls smoke.psv
---------- 1 groth groth 572 Jun 26 08:35 smoke.psv

**Comment by ehsannas** [comment]
I'm running something similar:

``dxc -T ps_6_0 smoke.hlsl -Fo temp``

(I get the same behavior with and without ``-spirv``)

> $ ll temp
---------- 1 ehsan ehsan 1052 Jun 26 10:56 temp

And the file ``temp`` is empty.

**Comment by ehsannas** [comment]
yeah permissions are also not what I want.

**Comment by pow2clk** [comment]
1052 indicates it's not empty. It's possible you can't see the contents because of the permissions. This is no kind of solution, but just to see, if you `chmod 644 temp`, can you view the contents?

**Comment by pow2clk** [comment]
Well shoot. I thought that, all things being equal, my file IO change seemed most likely to blame. And it is :frown: I'll look into it.

**Comment by ehsannas** [comment]
oh... sorry, I had just ran ``vim temp`` and saw no content. I failed to look at the file size from ``ls``.
Yes, after changing the permissions I do see the content.

**Comment by ehsannas** [comment]
I'll update the issue title.
