### ISSUE TITLE
A bug for a `StructuredBuffer`.

### ISSUE THREAD

**Issue by jaebaek** [google/DirectXShaderCompiler#303]
I found a bug for a `StructuredBuffer`.
See [this example](https://github.com/google/DirectXShaderCompiler/pull/302/files#diff-22af72015ed4316674dde91a77ef7857) which is not related to debug info.
It has a validation error saying
```
In Logical addressing, variables may not allocate a pointer type
  %counter_var_inputBuffer = OpVariable %_ptr_Private__ptr_Uniform_type_ACSBuffer_counter Private
```

When I previously tested it with spv-val, it worked fine without validation error.
I guess the error came from one of recent DXC commits.

@ehsannas Do you have any idea?

**Comment by ehsannas** [comment]
this error is from a non-legalized spir-v.

your source code passes just fine after legalization:
http://shader-playground.timjones.io/989fba21122c97d319d27ce25be63eb6
