### ISSUE TITLE
Apply binding shifts to resources without register assignments?

### ISSUE THREAD

**Issue by danginsburg** [google/DirectXShaderCompiler#316]
From what I have understood (and experimenting with dxc), the -fvk-*-shift arguments provide binding shifts only for those resources that have explicit register assignments.

From https://github.com/Microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst#implicit-binding-number-assignment it appears that one can provide a descriptor set and otherwise it auto generates a binding:

"If there is no register specification, the corresponding resource will be assigned to the next available binding number, starting from 0, in descriptor set #0 (If -auto-binding-space N command line option is used, then descriptor set #N will be used instead of descriptor set #0)."

In glslang, we use the --auto-map-bindings option which behaves a bit differently in that it auto numbers bindings, but it applies the binding shifts.  So basically what I am looking for is a way to do this:

SamplerState sampler0 : register( s2 );
SamplerState sampler1;
SamplerState sampler2;

I'd like to pass -fvk-s-shift 10 0 and have 

sampler0 <- descriptor set 0, binding 12
sampler1 <- descriptor set 0, binding 10
sampler2 <- descriptor set 0, binding 11

This is what glslang would do.  Is it possible to do this with dxc?

**Comment by ehsannas** [comment]
The Google fork of DXC is not actively monitored. Please file future issues in the upstream repository. 
(I've copied this issue to upstream https://github.com/microsoft/DirectXShaderCompiler/issues/2956)

Thanks!
