### ISSUE TITLE
Translate pixel shader writing constant value

### ISSUE THREAD

**Issue by antiagainst** [google/DirectXShaderCompiler#32]
**Goal**:
* Translate `float4 PSMain(): SV_TARGET { return float4(1.0f, 1.0f, 1.0f, 1.0f); }`

**Comment by ehsannas** [comment]
I've started looking into
`float4(1.0f, 1.0f, 1.0f, 1.0f);`

**Comment by ehsannas** [comment]
Done via PR #57
