### ISSUE TITLE
-fspv-debug=rich gives no spirv or error for shader with cbuffer of arrays of structs

### ISSUE THREAD

**Issue by greg-lunarg** [google/DirectXShaderCompiler#323]
@jaebaek FYI

This problem is caused by a proprietary shader. I have not been successful in creating a reduced case. I can give a full copy to whoever is working on this problem.

Here is the cbuffer that was being processed:

```
cbuffer PerViewLightData_t
{

    PointLight_t g_pointLightData [ 128 ] : packoffset ( c0 ) ;
    SpotLight_t g_spotLightData [ 128 ] : packoffset ( c384 ) ;
    ShadowedSpotLight_t g_shadowedSpotLightData [ 128 ] : packoffset ( c1024 ) ;
    EnvMapLight_t g_envMapData [ 128 ] : packoffset ( c1792 ) ;
} ;
```

Running in VS, I saw an assert tripped where some DebugInfo code was processing a member in aforementioned cbuffer and (erroneously) thought it was a method.

The assert was tripped in the following call to generateFunctionInfo() in LowerTypeVisitor.cpp:

```
  for (auto &memberDecl : decl->decls()) {
    if (const auto *cxxMethodDecl = dyn_cast<CXXMethodDecl>(memberDecl)) {
      auto *fn = spvContext.findFunctionInfo(cxxMethodDecl);
      if (fn) {
        fn->setParent(dbgTyComposite);
        members.push_back(fn);
      } else {
        members.push_back(generateFunctionInfo(cxxMethodDecl, dbgTyComposite));
      }
      continue;
    }
```

The assert was in getName() at this statement in generateFunctionInfo():

`std::string funcName = classOrStructName + decl->getName().str();`

Here is the assert in getName():

```
  StringRef getName() const {
    assert(Name.isIdentifier() && "Name is not a simple identifier");
    return getIdentifier() ? getIdentifier()->getName() : "";
  }
```

Running without -fspv-debug=rich produces valid SPIR-V file.

**Comment by jaebaek** [comment]
@greg-lunarg Thank you for reporting this bug

I think you used an old one. Could you please git-pull `debug_info` branch of google/DirectXShaderCompiler repo again?
I recently submitted a large PR that might fix this issue.

**Comment by jaebaek** [comment]
In addition, I just sent this PR: https://github.com/google/DirectXShaderCompiler/pull/327

It will allow us to run DXC with legalization (maybe without errors in most cases) even when we generate the debug information.

**Comment by jaebaek** [comment]
I will close this issue. Please let me know if it does not work.
