### ISSUE TITLE
-fspv-debug=rich not generating DebugFunction for entry point function

### ISSUE THREAD

**Issue by greg-lunarg** [google/DirectXShaderCompiler#324]
-fspv-debug=rich is not generating DebugFunction for the entry point function. In addition, it is generating a DebugFunction for an internal function that it probably should not generate.

Consider this shader:

```
Texture2D g_tColor;
SamplerState g_sAniso;

struct PS_INPUT
{
    float2 vTextureCoords : TEXCOORD2 ;
} ;

struct PS_OUTPUT
{
    float4 vColor : SV_Target0 ;
} ;

PS_OUTPUT MainPs ( PS_INPUT i )
{
    PS_OUTPUT ps_output ;
    float2 tc = i . vTextureCoords . xy;
    ps_output . vColor = g_tColor . Sample ( g_sAniso , tc ) ;
    return ps_output ;
}
```

The compiler is NOT generating a DebugFunction for MainPs. And it is generating a DebugFunction for an internal function called src.MainPs that the user does not need to know about.

The compiler should generate a DebugFunction for MainPs. And it should NOT generate a DebugFunction for the internal function src.MainPs.

FYI @jaebaek

**Comment by greg-lunarg** [comment]
@jaebaek Do you agree that this is a problem? If so, I will start working on a solution.

**Comment by jaebaek** [comment]
I do not think this is a bug.

This may sound weird but `%src_MainPs` in SPIR-V is `MainPs` in HLSL while `%MainPs` is a wrapper function that is just generated by compiler i.e., it does not exist in HLSL.
(I heard it from the main DXC developer that the main reason behind this wrapper function is that the entry point must not have a return value in Vulkan but HLSL allows functions to have returns, so we wanted to simulate it)

**Comment by greg-lunarg** [comment]
I will concede that the function %src_MainPs is indeed what should be presented to the user as the function called MainPs in the shader source.

I do still think there is a bug: if you look at the one DebugFunction that is created, it has a Name of "src.MainPs". I believe the value of this field should be "MainPs". Here is the definition of the Name operand for DebugFunction:

Name is an OpString, holding the name of the function as it appears in the source program

The name of the function in the source program is "MainPs".

As for the Linkage Name operand, it is currently "src.MainPs". Technically, I don't think this is correct either. This function is not externally visible and so it really does not have a linkage name. I would prefer to see it set to DebugInfoNone, but this is not currently valid according to the spec. My preference would be to ultimately change the spec to allow for DebugInfoNone here and set it to that. Its probably ok for the moment to leave it as "src.MainPs". Maybe better would be to make it the empty string "". We could probably do so for the Linkage Name of all internal functions. It certainly should NOT be changed to "MainPs" along with the Name.

**Comment by jaebaek** [comment]
Ah I see. Yes, it is a bug. I will change the name to `MainPs` not `src.MainPs`. In terms of the linkage name, yes, I agree with you but we try to avoid changing the type of operand if it is possible because of the backward compatibility. The empty string "" looks good to me. Let me update it.
