### ISSUE TITLE
Provide some experimental build?

### ISSUE THREAD

**Issue by oscarbg** [google/DirectXShaderCompiler#35]
Hi,
can enable artifacts in Appveyor?
so we have SPIR-V experimental builds to play..
thanks..

**Comment by antiagainst** [comment]
Thanks for the suggestion!

Right now we are still at the early stage of development; little HLSL features are covered thus far. I'll keep this issue open so we can try to set it up later when we have some basic coverage. :)

**Comment by antiagainst** [comment]
Hi @oscarbg,

I've created https://github.com/Microsoft/DirectXShaderCompiler/pull/641 which will do the trick. Thanks!

**Comment by antiagainst** [comment]
Microsoft#641 is merged. This is done now.

**Comment by oscarbg** [comment]
Thanks!
just a minor request:
can you generate a zipped file as a result artifact instead of the 17 files so we can get easily downloading from a browser..

**Comment by antiagainst** [comment]
That is reasonable. But I think some of the artifacts are not interesting at all. So need to trim the list. Will zip the rest then.

I'll reopen this issue to track the progress.

**Comment by oscarbg** [comment]
thanks..
I written a very simple script to download all.. 
changing build job id in script should work for future builds..

getarti.bat
```
@echo off
set JOBID=1994p38mho0l10ma
start baja %JOBID% clang-hlsl-tests.dll
start baja %JOBID% clang-spirv-tests.exe
start baja %JOBID% clang-tblgen.exe
start baja %JOBID% d3dcompiler_dxc_bridge.dll
start baja %JOBID% dndxc.exe
start baja %JOBID% dxa.exe
start baja %JOBID% dxc.exe
start baja %JOBID% dxcompiler.dll
start baja %JOBID% dxc_batch.exe
start baja %JOBID% dxexp.exe
start baja %JOBID% dxl.exe
start baja %JOBID% dxlib_sample.dll
start baja %JOBID% dxopt.exe
start baja %JOBID% dxr.exe
start baja %JOBID% dxv.exe
start baja %JOBID% HLSLHost.exe
start baja %JOBID% llvm-tblgen.exe
```
baja.bat
```
@echo off
echo Downloading "https://ci.appveyor.com/api/buildjobs/%1/artifacts/build/Debug/bin/%2"..
wget "https://ci.appveyor.com/api/buildjobs/%1/artifacts/build/Debug/bin/%2" -q
exit
```

**Comment by antiagainst** [comment]
FYI: https://github.com/Microsoft/DirectXShaderCompiler/pull/647 zips all build artifacts.

**Comment by antiagainst** [comment]
Microsoft#647 is merged. I'll close this issue now.
