### ISSUE TITLE
Handle execution mode

### ISSUE THREAD

**Issue by ehsannas** [google/DirectXShaderCompiler#40]
**Goals**
* Emit the correct `OpExecutionMode` for `void main() {}` as pixel shader

**Comment by ehsannas** [comment]
pull #41 adds `OpExecutionMode` with the correct function id target. However, it currently uses OriginUpperLeft as the default execution mode.

Keeping this issue open to implement the logic for determining the execution mode based on shader stage, semantics, etc.

**Comment by antiagainst** [comment]
Can be marked as done once #41 is merged since it's only asking for the execution mode for `void main() {}` as pixel shader.

**Comment by antiagainst** [comment]
Design?: N/A
Pull request: #41 
Test coverage: #41 
Verifer: @antiagainst
