### ISSUE TITLE
Consider simplifying the InstBuilder API

### ISSUE THREAD

**Issue by ehsannas** [google/DirectXShaderCompiler#43]
@antiagainst 
At some point we should think again about whether it still makes sense to use a "word consumer" for the instruction builder. Instead, we could have the ".x()" function return the word vector.

For instance, I just wrote the following code in a pull request:

```cpp
std::vector<uint32_t> execModeInstr;
spirv::InstBuilder ib([&execModeInstr](std::vector<uint32_t> &&words) {
  execModeInstr = std::move(words);
});
ib.opExecutionMode(funcId, spv::ExecutionMode::OriginUpperLeft).x();
```

If the above change is made, the above code would be simplified to:
```cpp
auto& instr = InstrBuilder().opExecutionMode(funcId, spv::ExecutionMode::OriginUpperLeft).x();
```

If there is any good example of the WordConsumer functor being useful, we can keep things as they are.

**Comment by antiagainst** [comment]
The `WordConsumer` is useful for collecting multiple instructions, e.g., when calling `take()` on the module. But what listed above definitely makes sense. We should have another method for just constructing and returning a single instruction.

**Comment by antiagainst** [comment]
We already have it.
