### ISSUE TITLE
Translate pass-through compute shader using "Raw Buffers"

### ISSUE THREAD

**Issue by antiagainst** [google/DirectXShaderCompiler#53]

**Comment by ehsannas** [comment]
Goals:
* Write pass-through compute shader in HLSL
* Work towards getting the equivalent SPIR-V module in the hlsl2spirv flow

**Comment by ehsannas** [comment]
source: https://msdn.microsoft.com/en-us/library/windows/desktop/ff476330(v=vs.85).aspx
Using the above as source, I have written the following HLSL compute shader:

```
//--------------------------------------------------------------------------------------
// This file contains the Compute Shader to perform out = in
// Uses RAW Buffers
//--------------------------------------------------------------------------------------

ByteAddressBuffer Buffer0 : register(t0);
RWByteAddressBuffer BufferOut : register(u0);

[numthreads(1, 1, 1)]
void CSMain( uint3 DTid : SV_DispatchThreadID )
{
    float f0 = asfloat( Buffer0.Load( DTid.x*4 ) );
    BufferOut.Store( DTid.x*4, asuint(f0) );
}
```

**Comment by ehsannas** [comment]
ByteAddressBuffer and RWByteAddressBuffer type translation was added via mr #157

**Comment by ehsannas** [comment]
Translation for Load, Load2, Load3, Load4 is under review via PR #159

**Comment by ehsannas** [comment]
Translation of Store, Store2, Store3, Store4 is under review via pr #162 .

**Comment by antiagainst** [comment]
This is landed as https://github.com/Microsoft/DirectXShaderCompiler/commit/a4efd3babca66c446d157c697992b2909e42bbc0
